#if !defined(AFX_GENROWCURSOR_H__31420B06_C3B5_11D3_B2C3_005004131224__INCLUDED_)
#define AFX_GENROWCURSOR_H__31420B06_C3B5_11D3_B2C3_005004131224__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CGenRowCursor wrapper class

class AFX_EXT_CLASS CGenRowCursor : public COleDispatchDriver
{
public:
	CGenRowCursor() {}		// Calls COleDispatchDriver default constructor
	CGenRowCursor(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CGenRowCursor(const CGenRowCursor& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GENROWCURSOR_H__31420B06_C3B5_11D3_B2C3_005004131224__INCLUDED_)
