#ifndef __HRESULTS_H_
#define __HRESULTS_H_

// MsiCommon
#include "msicommonerrors.h"

#define E_IS_DUP_PRIMARY MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1000)
#define E_IS_TEMPFILE_CREATION_FAILED MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1001)
#define E_IS_RESTORATION_FROM_TEMPFILE_FAILED MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1002)
#define E_IS_PROJECT_ALREADY_OPEN MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1003)
#define E_IS_FILENAME_ALREADY_EXISTS MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1004)
#define E_IS_DIRECTORY_PREDEFINED_FOLDER_NOT_FOUND MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1005)
#define E_IS_DIRECTORY_INVALID_PATH_FORMAT MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1006)
#define E_IS_DIRECTORY_ERROR_ADDING_NEW MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1007)
#define E_IS_DIRECTORY_ERROR_INSTALLDIR_MISSING MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1008)
#define E_IS_DIRECTORY_ERROR_INVALID_INSTALLDIR_VALUE MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1009)
#define E_IS_DIRECTORY_ERROR_ADDING_PREDEFINED MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1010)
#define E_IS_DIRECTORY_ERROR_DOT_NOT_ALLOWED MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1011)
#define E_IS_DIRECTORY_ERROR_COLON_NOT_ALLOWED MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1012)
#define E_IS_NO_TEMP_DIR MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1013)
#define E_IS_DIRECTORY_ENTRY_ORPHANED MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1014)
#define E_IS_SET_DATABASE_CODEPAGE_FAILED MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1015)
#define E_IS_FAILED_TO_LOAD_MODULE MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1016)
#define E_IS_PROJECT_OPEN_DIRECT_READONLY MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1017)
#define E_IS_LOCK_PROJECT_FAILED MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1018)
#define E_IS_UNLOCK_PROJECT_FAILED MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1019)
#define E_IS_GET_TEMP_FILENAME_FAILED MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1020)
#define E_IS_SET_TEMP_FILE_ATTRIBUTES_FAILED MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1021)
#define E_IS_SET_PROJECT_READONLY_STATUS MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1022)
#define E_IS_ISV_OLD_VERSION_HRESULT MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1023)
#define E_IS_DIRECTORY_DELETED_INSTALLDIR MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1024)
#define E_IS_INVALID_KEY MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1025) // cannot have certain characters, like '
#define E_IS_PATCHWDLL_MISSING_MSP_FILE MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1026) 
#define E_IS_APPLY_MST MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1027) 
#define E_IS_TOO_MANY_PROGIDS MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1028) 
#define E_IS_INVALID_SELFREGISTER_FILE_EXTENSION MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1029) 
#define E_IS_FILE_NON_EXECUTABLE MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1030) 
#define E_IS_REGISTER_FAILED MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1031) 
#define E_IS_UNREGISTER_FAILED MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1032) 
#define E_IS_DIRECTORY_ERROR_HARDCODED_NOT_ALLOWED MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1033)
#define E_IS_DEPFILEGROUP_FEATURENAMES_NOT_SET MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1034)
#define E_IS_INVALID_RUNTIME_TEXTSUB_NAME MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1035)
#define E_IS_SCRIPT_CUSTOM_ACTION_GET_REFERENCE_OBJECT_FAILED MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1036)
#define E_LOCKPERMS_CONVERSION_UNSUPPORTED_USER_VALUE MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1037)
#define E_LOCKPERMS_CONVERSION_UNSUPPORTED_ATTRIBUTES_VALUE MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1038)
#define E_IS_INVALID_FILENAME MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1039)

#endif __HRESULTS_H_