#ifndef _ISCMSERVICESDISPID_H_
#define _ISCMSERVICESDISPID_H_

//	ISCMServicesEvents
#define DISPID_SERVICESVALIDATION		51   
#define DISPID_IMPORTPROGRESS_TABLE		52
#define DISPID_IMPORTERROR				53   
#define DISPID_IMPORTFINISH				54
#define DISPID_IMPORTPROGRESS_RECORD	55
#define DISPID_TABLE_IMPORTFINISH		56

#define DISPID_SYNCHRONIZE_DATABASE		57
#define DISPID_SYNCHRONIZE_PACKAGE		58
#define DISPID_SYNCHRONIZE_TABLE		59
#define DISPID_SYNCHRONIZE_RECORD		60
#define DISPID_SYNCHRONIZEFINISH		61

#define DISPID_EVALUATIONMESSAGE		101
#define DISPID_EVALUATIONPROGRESS		102
#define DISPID_EVALUATIONSUBPROGRESS	103

//	ISCMEvaluatorEvents
#endif // _ISCMSERVICESDISPID_H_
