//===========================================================================
//
//  IIIIIII SSSSSS
//    II    SS                          InstallShield (R
//    II    SSSSSS      (c) 1996-2003, InstallShield Software Corporation
//    II        SS      (c) 1990-1996, InstallShield Corporation
//  IIIIIII SSSSSS                     All Rights Reserved.
//
//
//    File Name:  SetupTraceDefs.h
//	
//  Description:  Setup Tracing defintions
//
//===========================================================================

#ifndef _SETUPTRACEDEFS_H_
#define _SETUPTRACEDEFS_H_

#include "SetupTraceDefsPriv.h"

//
// !!!IMPORTANT NOTE!!!
// 
// Don't use #pragma or _T() notation nor the \ line continuation character
// in this file, since it needs to be compilable with the InstallScript compiler.
//

// General ******************************************************************

// For InstallScript compiler use + to seperate strings, for C++ compiler no delimiter
// is needed.
#ifdef _ISCRIPT_VER
#define TRACE_PLUS											+
#else
#define TRACE_PLUS
#endif

#define TRACE_FMT_HEXVALUE_TAB								_T("0x%08lx") TRACE_PLUS TRACE_FMT_TAB
#define TRACE_FMT_DECVALUE_TAB								_T("%ld") TRACE_PLUS TRACE_FMT_TAB
#define TRACE_FMT_STRVALUE_TAB								_T("%s") TRACE_PLUS TRACE_FMT_TAB
#define TRACE_FMT_STRWVALUE_TAB								_T("%S") TRACE_PLUS TRACE_FMT_TAB

#define TRACE_FMT_HEXVALUE_TAB_PLUS							TRACE_PLUS _T("0x%08lx") TRACE_PLUS TRACE_FMT_TAB TRACE_PLUS
#define TRACE_FMT_DECVALUE_TAB_PLUS							TRACE_PLUS _T("%ld") TRACE_PLUS TRACE_FMT_TAB TRACE_PLUS
#define TRACE_FMT_STRVALUE_TAB_PLUS							TRACE_PLUS _T("%s") TRACE_PLUS TRACE_FMT_TAB TRACE_PLUS
#define TRACE_FMT_STRWVALUE_TAB_PLUS						TRACE_PLUS _T("%S") TRACE_PLUS TRACE_FMT_TAB TRACE_PLUS

#define TRACE_FMT_TAB_PLUS									TRACE_PLUS TRACE_FMT_TAB TRACE_PLUS

#define TRACE_TXT_SUCCESS									_T("Success")
#define TRACE_TXT_FAILURE									_T("Failure")
#define TRACE_TXT_YES										_T("Yes")
#define TRACE_TXT_NO										_T("No")
#define TRACE_TXT_CREATED									_T("Created")
#define TRACE_TXT_NOTCREATED								_T("NotCreated")
#define TRACE_TXT_COPIED                                    _T("Copied")
#define TRACE_TXT_NOTCOPIED                                 _T("NotCopied")
#define TRACE_TXT_FOUND                                     _T("Found")
#define TRACE_TXT_NOTFOUND                                  _T("NotFound")
#define TRACE_TXT_INSTALLED                                 _T("Installed")
#define TRACE_TXT_NOTINSTALLED                              _T("NotInstalled")
#define TRACE_TXT_INSTALL                                   _T("Install")
#define TRACE_TXT_DONTINSTALL                               _T("DontInstall")

#define TRACE_FMT_RESULT									_T("Result=") TRACE_PLUS TRACE_FMT_STRVALUE_TAB
#define TRACE_FMT_RESULT_NOTAB								_T("Result=") TRACE_PLUS TRACE_FMT_STRVALUE
#define TRACE_FMT_ERROR										_T("Error=") TRACE_PLUS TRACE_FMT_HEXVALUE_TAB
#define TRACE_FMT_GETLASTERROR								_T("GetLastError=") TRACE_PLUS TRACE_FMT_HEXVALUE_TAB
#define TRACE_FMT_RESULT_ERROR								TRACE_FMT_RESULT TRACE_FMT_TAB_PLUS TRACE_FMT_ERROR

// OSInfo *******************************************************************
#define TRACE_CAT_OSINFO									_T("ISSYSINFO")
#define TRACE_SUB_SYSINFO									_T("ISSYSINFO")

// SysVars ******************************************************************
#define TRACE_CAT_SYSVARS									_T("ISSYSVARS")
#define TRACE_SUB_SYSVARS									_T("ISSYSVARS")

// IS Functions *************************************************************
#define TRACE_CAT_ISFUNC_BEGIN								_T("ISFuncBegin")
#define TRACE_CAT_ISFUNC_END								_T("ISFuncEnd")

// Feature Related ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// FeatureMoveData
#define TRACE_SUB_ISFUNC_FEATUREMOVEDATA					_T("FeatureMoveData")
#define TRACE_FMT_ISFUNC_FEATUREMOVEDATA					_T("Media=") TRACE_FMT_STRVALUE
#define TRACE_FMT_ISFUNC_FEATUREMOVEDATA_RESULT				TRACE_FMT_RESULT TRACE_FMT_TAB TRACE_FMT_ISFUNC_FEATUREMOVEDATA
#define TRACE_FMT_ISFUNC_FEATUREMOVEDATA_RESULT_ERROR		TRACE_FMT_RESULT_ERROR TRACE_FMT_TAB TRACE_FMT_ISFUNC_FEATUREMOVEDATA

// FeatureTransferData
#define TRACE_SUB_ISFUNC_FEATURETRANSFERDATA				_T("FeatureTransferData")
#define TRACE_FMT_ISFUNC_FEATURETRANSFERDATA				_T("Media=") TRACE_FMT_STRVALUE
#define TRACE_FMT_ISFUNC_FEATURETRANSFERDATA_RESULT			TRACE_FMT_RESULT TRACE_FMT_TAB TRACE_FMT_ISFUNC_FEATURETRANSFERDATA
#define TRACE_FMT_ISFUNC_FEATURETRANSFERDATA_RESULT_ERROR	TRACE_FMT_RESULT_ERROR TRACE_FMT_TAB TRACE_FMT_ISFUNC_FEATURETRANSFERDATA

// FeatureLoadTarget
#define TRACE_SUB_ISFUNC_FEATURELOADTARGET					_T("FeatureLoadTarget")
#define TRACE_FMT_ISFUNC_FEATURELOADTARGET					_T("Name=") TRACE_FMT_STRVALUE
#define TRACE_FMT_ISFUNC_FEATURELOADTARGET_RESULT			TRACE_FMT_RESULT TRACE_FMT_TAB TRACE_FMT_ISFUNC_FEATURELOADTARGET
#define TRACE_FMT_ISFUNC_FEATURELOADTARGET_RESULT_ERROR		TRACE_FMT_RESULT_ERROR TRACE_FMT_ISFUNC_FEATURELOADTARGET

// FeatureSaveTarget
#define TRACE_SUB_ISFUNC_FEATURESAVETARGET					_T("FeatureSaveTarget")
#define TRACE_FMT_ISFUNC_FEATURESAVETARGET					_T("Name=") TRACE_FMT_STRVALUE
#define TRACE_FMT_ISFUNC_FEATURESAVETARGET_RESULT			TRACE_FMT_RESULT TRACE_FMT_TAB TRACE_FMT_ISFUNC_FEATURESAVETARGET
#define TRACE_FMT_ISFUNC_FEATURESAVETARGET_RESULT_ERROR		TRACE_FMT_RESULT_ERROR TRACE_FMT_ISFUNC_FEATURESAVETARGET

// CreateDir
#define TRACE_SUB_ISFUNC_CREATEDIR							_T("CreateDir")
#define TRACE_FMT_ISFUNC_CREATEDIR							_T("Dir=") TRACE_FMT_STRVALUE
#define TRACE_FMT_ISFUNC_CREATEDIR_RESULT					TRACE_FMT_RESULT TRACE_FMT_TAB TRACE_FMT_ISFUNC_CREATEDIR
#define TRACE_FMT_ISFUNC_CREATEDIR_RESULT_ERROR				TRACE_FMT_RESULT_ERROR TRACE_FMT_TAB TRACE_FMT_ISFUNC_CREATEDIR

// DeleteDir
#define TRACE_SUB_ISFUNC_DELETEDIR							_T("DeleteDir")
#define TRACE_FMT_ISFUNC_DELETEDIR							_T("Dir=") TRACE_FMT_STRVALUE_TAB_PLUS _T("Flags=") TRACE_PLUS TRACE_FMT_HEXVALUE
#define TRACE_FMT_ISFUNC_DELETEDIR_RESULT					TRACE_FMT_RESULT TRACE_FMT_TAB_PLUS TRACE_FMT_ISFUNC_DELETEDIR
#define TRACE_FMT_ISFUNC_DELETEDIR_RESULT_ERROR				TRACE_FMT_RESULT_ERROR TRACE_FMT_TAB_PLUS TRACE_FMT_ISFUNC_DELETEDIR

// XCopyFile
#define TRACE_SUB_ISFUNC_XCOPYFILE							_T("XCopyFile")
#define TRACE_FMT_ISFUNC_XCOPYFILE							_T("Source=") TRACE_FMT_STRVALUE_TAB _T("Target=") TRACE_FMT_STRVALUE_TAB _T("Flags=") TRACE_FMT_HEXVALUE
#define TRACE_FMT_ISFUNC_XCOPYFILE_RESULT					TRACE_FMT_RESULT TRACE_FMT_TAB TRACE_FMT_ISFUNC_XCOPYFILE
#define TRACE_FMT_ISFUNC_XCOPYFILE_RESULT_ERROR				TRACE_FMT_RESULT_ERROR TRACE_FMT_TAB TRACE_FMT_ISFUNC_XCOPYFILE

// DeleteFile
#define TRACE_SUB_ISFUNC_DELETEFILE							_T("DeleteFile")
#define TRACE_FMT_ISFUNC_DELETEFILE							_T("File=") TRACE_PLUS TRACE_FMT_STRVALUE
#define TRACE_FMT_ISFUNC_DELETEFILE_RESULT					TRACE_FMT_RESULT TRACE_FMT_TAB_PLUS TRACE_FMT_ISFUNC_DELETEFILE
#define TRACE_FMT_ISFUNC_DELETEFILE_RESULT_ERROR			TRACE_FMT_RESULT_ERROR TRACE_FMT_TAB_PLUS TRACE_FMT_ISFUNC_DELETEFILE

// RenameFile
#define TRACE_SUB_ISFUNC_RENAMEFILE			    	    	_T("RenameFile")
#define TRACE_FMT_ISFUNC_RENAMEFILE				    		_T("FileNameOld=") TRACE_FMT_STRVALUE_TAB_PLUS _T("FileNameNew=") TRACE_PLUS TRACE_FMT_STRVALUE
#define TRACE_FMT_ISFUNC_RENAMEFILE_RESULT					TRACE_FMT_RESULT TRACE_FMT_TAB_PLUS TRACE_FMT_ISFUNC_RENAMEFILE
#define TRACE_FMT_ISFUNC_RENAMEFILE_RESULT_ERROR			TRACE_FMT_RESULT_ERROR TRACE_FMT_TAB_PLUS TRACE_FMT_ISFUNC_RENAMEFILE

// CoGetObject
#define TRACE_SUB_ISFUNC_COGETOBJECT		                _T("CoGetObject")
#define TRACE_FMT_ISFUNC_COGETOBJECT                        _T("File=") TRACE_FMT_STRVALUE_TAB _T("ProgId=") TRACE_FMT_STRVALUE
#define TRACE_FMT_ISFUNC_COGETOBJECT_RESULT                 TRACE_FMT_RESULT TRACE_FMT_ISFUNC_COGETOBJECT TRACE_FMT_TAB _T("DispId=") TRACE_FMT_HEXVALUE
#define TRACE_FMT_ISFUNC_COGETOBJECT_RESULT_ERROR           TRACE_FMT_RESULT_ERROR TRACE_FMT_ISFUNC_COGETOBJECT TRACE_FMT_TAB _T("DispId=") TRACE_FMT_HEXVALUE

// CoCreateObject
#define TRACE_SUB_ISFUNC_COCREATEOBJECT		                _T("CoCreateObject")
#define TRACE_FMT_ISFUNC_COCREATEOBJECT                     _T("ProgId=") TRACE_FMT_STRVALUE
#define TRACE_FMT_ISFUNC_COCREATEOBJECT_RESULT              TRACE_FMT_RESULT TRACE_FMT_ISFUNC_COCREATEOBJECT TRACE_FMT_TAB _T("DispId=") TRACE_FMT_HEXVALUE

// Shell Object Related +++++++++++++++++++++++++++++++++++++++++++++++++++++
#ifndef _ISCRIPT_VER // Note: IS Compiler has problems with large macros, for now avoid by not compiling this
                     // code when InstallScript is being compiled.

// AddFolderIcon
#define TRACE_SUB_ISFUNC_ADDFOLDERICON						_T("AddFolderIcon")
#define TRACE_FMT_ISFUNC_ADDFOLDERICON						_T("ProgramFolder=") TRACE_FMT_STRVALUE_TAB_PLUS _T("ItemName=") TRACE_FMT_STRVALUE_TAB_PLUS _T("CommandLine= ") TRACE_FMT_STRVALUE TRACE_FMT_TAB_PLUS _T("WorkingDir=") TRACE_FMT_STRVALUE_TAB_PLUS _T("IconFile=") TRACE_FMT_STRVALUE_TAB_PLUS _T("IconIndex=") TRACE_FMT_DECVALUE_TAB_PLUS _T("ShortcutKey=") TRACE_FMT_STRVALUE_TAB_PLUS _T("Flags=") TRACE_FMT_DECVALUE
#define TRACE_FMT_ISFUNC_ADDFOLDERICON_RESULT				TRACE_FMT_RESULT TRACE_FMT_TAB TRACE_FMT_ISFUNC_ADDFOLDERICON
#define TRACE_FMT_ISFUNC_ADDFOLDERICON_RESULT_ERROR			TRACE_FMT_RESULT_ERROR TRACE_FMT_TAB_PLUS TRACE_FMT_ISFUNC_ADDFOLDERICON

// CreateProgramFolder
#define TRACE_SUB_ISFUNC_CREATEPROGRAMFOLDER				_T("CreateProgramFolder")
#define TRACE_FMT_ISFUNC_CREATEPROGRAMFOLDER				_T("Folder=") TRACE_FMT_STRVALUE
#define TRACE_FMT_ISFUNC_CREATEPROGRAMFOLDER_RESULT			TRACE_FMT_RESULT TRACE_FMT_TAB TRACE_FMT_ISFUNC_CREATEPROGRAMFOLDER
#define TRACE_FMT_ISFUNC_CREATEPROGRAMFOLDER_RESULT_ERROR	TRACE_FMT_RESULT_ERROR TRACE_FMT_ISFUNC_CREATEPROGRAMFOLDER

// DeleteProgramFolder
#define TRACE_SUB_ISFUNC_DELETEPROGRAMFOLDER				_T("DeleteProgramFolder")
#define TRACE_FMT_ISFUNC_DELETEPROGRAMFOLDER				_T("Folder=") TRACE_FMT_STRVALUE
#define TRACE_FMT_ISFUNC_DELETEPROGRAMFOLDER_RESULT			TRACE_FMT_RESULT TRACE_FMT_TAB TRACE_FMT_ISFUNC_DELETEPROGRAMFOLDER
#define TRACE_FMT_ISFUNC_DELETEPROGRAMFOLDER_RESULT_ERROR	TRACE_FMT_RESULT_ERROR TRACE_FMT_ISFUNC_DELETEPROGRAMFOLDER

// DeleteFolderIcon
#define TRACE_SUB_ISFUNC_DELETEFOLDERICON					_T("DeleteFolderIcon")
#define TRACE_FMT_ISFUNC_DELETEFOLDERICON					_T("Icon=") TRACE_FMT_STRVALUE
#define TRACE_FMT_ISFUNC_DELETEFOLDERICON_RESULT			TRACE_FMT_RESULT TRACE_FMT_TAB TRACE_FMT_ISFUNC_DELETEFOLDERICON
#define TRACE_FMT_ISFUNC_DELETEFOLDERICON_RESULT_ERROR		TRACE_FMT_RESULT_ERROR TRACE_FMT_ISFUNC_DELETEFOLDERICON

// ReplaceFolderIcon
#define TRACE_SUB_ISFUNC_REPLACEFOLDERICON					_T("ReplaceFolderIcon")
#define TRACE_FMT_ISFUNC_REPLACEFOLDERICON					_T("ProgramFolder=") TRACE_FMT_STRVALUE TRACE_FMT_TAB _T("ItemName=") TRACE_FMT_STRVALUE TRACE_FMT_TAB _T("NewItemName=") TRACE_FMT_STRVALUE TRACE_FMT_TAB _T("CommandLine=") TRACE_FMT_STRVALUE TRACE_FMT_TAB _T("WorkingDir=") TRACE_FMT_STRVALUE TRACE_FMT_TAB _T("IconPath=") TRACE_FMT_STRVALUE TRACE_FMT_TAB _T("Icon=") TRACE_FMT_DECVALUE TRACE_FMT_TAB _T("ShortcutKey=") TRACE_FMT_STRVALUE TRACE_FMT_TAB _T("Flags=") TRACE_FMT_DECVALUE
#define TRACE_FMT_ISFUNC_REPLACEFOLDERICON_RESULT			TRACE_FMT_RESULT TRACE_FMT_TAB TRACE_FMT_ISFUNC_REPLACEFOLDERICON
#define TRACE_FMT_ISFUNC_REPLACEFOLDERICON_RESULT_ERROR		TRACE_FMT_RESULT_ERROR TRACE_FMT_ISFUNC_REPLACEFOLDERICON

// CreateShellObjects
#define TRACE_SUB_ISFUNC_CREATESHELLOBJECTS                 _T("CreateShellObjects")

#endif // #ifndef _ISCRIPT_VER
// Registry Related +++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// RegDBCreateKeyEx
#define TRACE_SUB_ISFUNC_REGDBCREATEKEYEX					_T("RegDBCreateKeyEx")
#define TRACE_FMT_ISFUNC_REGDBCREATEKEYEX					_T("RootKey=") TRACE_FMT_DECVALUE TRACE_FMT_TAB _T("Key=") TRACE_FMT_STRVALUE TRACE_FMT_TAB _T("Class=") TRACE_FMT_STRVALUE TRACE_FMT_TAB _T("Shared=") TRACE_FMT_DECVALUE
#define TRACE_FMT_ISFUNC_REGDBCREATEKEYEX_RESULT			TRACE_FMT_RESULT TRACE_FMT_TAB TRACE_FMT_ISFUNC_REGDBCREATEKEYEX
#define TRACE_FMT_ISFUNC_REGDBCREATEKEYEX_RESULT_ERROR		TRACE_FMT_RESULT_ERROR TRACE_FMT_ISFUNC_REGDBCREATEKEYEX

// RegDBDeleteKey
#define TRACE_SUB_ISFUNC_REGDBDELETEKEY						_T("RegDBDeleteKey")
#define TRACE_FMT_ISFUNC_REGDBDELETEKEY						_T("RootKey=") TRACE_FMT_DECVALUE TRACE_FMT_TAB _T("Key=") TRACE_FMT_STRVALUE
#define TRACE_FMT_ISFUNC_REGDBDELETEKEY_RESULT				TRACE_FMT_RESULT TRACE_FMT_TAB TRACE_FMT_ISFUNC_REGDBDELETEKEY
#define TRACE_FMT_ISFUNC_REGDBDELETEKEY_RESULT_ERROR		TRACE_FMT_RESULT_ERROR TRACE_FMT_ISFUNC_REGDBDELETEKEY

// RegDBDeleteValue
#define TRACE_SUB_ISFUNC_REGDBDELETEVALUE					_T("RegDBDeleteValue")
#define TRACE_FMT_ISFUNC_REGDBDELETEVALUE					_T("RootKey=") TRACE_FMT_DECVALUE TRACE_FMT_TAB _T("Key=") TRACE_FMT_STRVALUE TRACE_FMT_TAB _T("Value=") TRACE_FMT_STRVALUE
#define TRACE_FMT_ISFUNC_REGDBDELETEVALUE_RESULT			TRACE_FMT_RESULT TRACE_FMT_TAB TRACE_FMT_ISFUNC_REGDBDELETEVALUE
#define TRACE_FMT_ISFUNC_REGDBDELETEVALUE_RESULT_ERROR		TRACE_FMT_RESULT_ERROR TRACE_FMT_ISFUNC_REGDBDELETEVALUE

// RegDBSetKeyValueEx
#define TRACE_SUB_ISFUNC_REGDBSETKEYVALUEEX					_T("RegDBSetKeyValueEx")
#define TRACE_FMT_ISFUNC_REGDBSETKEYVALUEEX					_T("RootKey=") TRACE_FMT_DECVALUE TRACE_FMT_TAB _T("Key=") TRACE_FMT_STRVALUE TRACE_FMT_TAB _T("ValueName=") TRACE_FMT_STRVALUE TRACE_FMT_TAB _T("ValueType=") TRACE_FMT_DECVALUE TRACE_FMT_TAB _T("Value=") TRACE_FMT_STRVALUE TRACE_FMT_TAB _T("ValueSize=") TRACE_FMT_DECVALUE
#define TRACE_FMT_ISFUNC_REGDBSETKEYVALUEEX_RESULT			TRACE_FMT_RESULT TRACE_FMT_TAB TRACE_FMT_ISFUNC_REGDBSETKEYVALUEEX
#define TRACE_FMT_ISFUNC_REGDBSETKEYVALUEEX_RESULT_ERROR	TRACE_FMT_RESULT_ERROR TRACE_FMT_ISFUNC_REGDBSETKEYVALUEEX

// CreateRegistrySet
#define TRACE_SUB_ISFUNC_CREATEREGISTRYSET                  _T("CreateRegistrySet")
#define TRACE_FMT_ISFUNC_CREATEREGISTRYSET                  _T("RegistrySet=") TRACE_FMT_STRVALUE                
#define TRACE_FMT_ISFUNC_CREATEREGISTRYSET_ERROR            TRACE_FMT_RESULT TRACE_FMT_ISFUNC_CREATEREGISTRYSET               
#define TRACE_FMT_ISFUNC_CREATEREGISTRYSET_RESULT_ERROR     TRACE_FMT_RESULT_ERROR  TRACE_FMT_ISFUNC_CREATEREGISTRYSET              

// External Related +++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// LaunchApp/LaunchAppAndWait
#define TRACE_SUB_ISFUNC_LAUNCHAPP							_T("LaunchApp")
#define TRACE_FMT_ISFUNC_LAUNCHAPP							_T("Program=") TRACE_FMT_STRVALUE_TAB_PLUS _T("CommandLine=") TRACE_FMT_STRVALUE_TAB_PLUS _T("Options=") TRACE_PLUS TRACE_FMT_DECVALUE
#define TRACE_FMT_ISFUNC_LAUNCHAPP_RESULT					TRACE_FMT_RESULT TRACE_PLUS TRACE_FMT_ISFUNC_LAUNCHAPP
#define TRACE_FMT_ISFUNC_LAUNCHAPP_RESULT_ERROR				TRACE_FMT_RESULT_ERROR TRACE_PLUS TRACE_FMT_ISFUNC_LAUNCHAPP

// UseDll/UnUseDll
#define TRACE_SUB_ISFUNC_USEDLL								_T("UseDLL")
#define TRACE_SUB_ISFUNC_UNUSEDLL							_T("UnUseDLL")
#define TRACE_FMT_ISFUNC_USEDLL								_T("Library=") TRACE_FMT_STRVALUE 
#define TRACE_FMT_ISFUNC_USEDLL_RESULT						TRACE_FMT_RESULT TRACE_FMT_TAB TRACE_FMT_ISFUNC_USEDLL
#define TRACE_FMT_ISFUNC_USEDLL_RESULT_ERROR				TRACE_FMT_RESULT_ERROR TRACE_FMT_ISFUNC_USEDLL

// CallDllFx
#define TRACE_SUB_ISFUNC_CALLDLLFX							_T("CallDllFx")
#define TRACE_FMT_ISFUNC_CALLDLLFX							_T("Dll=") TRACE_FMT_STRVALUE_TAB _T("Function=") TRACE_FMT_STRVALUE_TAB _T("Param00=") TRACE_FMT_HEXVALUE_TAB _T("Param01=") TRACE_FMT_STRVALUE
#define TRACE_FMT_ISFUNC_CALLDLLFX_RESULT					TRACE_FMT_RESULT TRACE_FMT_ISFUNC_CALLDLLFX
#define TRACE_FMT_ISFUNC_CALLDLLFX_RESULT_ERROR				TRACE_FMT_RESULT_ERROR TRACE_FMT_ISFUNC_CALLDLLFX

// IniFile Related ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// AddProfString
#define TRACE_SUB_ISFUNC_ADDPROFSTRING						_T("AddProfString")
#define TRACE_FMT_ISFUNC_ADDPROFSTRING						_T("FileName=") TRACE_FMT_STRVALUE_TAB_PLUS _T("SectionName=") TRACE_FMT_STRVALUE_TAB_PLUS _T("KeyName=") TRACE_FMT_STRVALUE_TAB_PLUS _T("ValueName=") TRACE_PLUS TRACE_FMT_STRVALUE
#define TRACE_FMT_ISFUNC_ADDPROFSTRING_RESULT				TRACE_FMT_RESULT TRACE_PLUS TRACE_FMT_ISFUNC_ADDPROFSTRING

// ReplaceProfString
#define TRACE_SUB_ISFUNC_REPLACEPROFSTRING					_T("ReplaceProfString")
#define TRACE_FMT_ISFUNC_REPLACEPROFSTRING					_T("FileName=") TRACE_FMT_STRVALUE_TAB_PLUS _T("SectionName=") TRACE_FMT_STRVALUE_TAB_PLUS _T("KeyName=") TRACE_FMT_STRVALUE_TAB_PLUS _T("OrigValueName=") TRACE_FMT_STRVALUE_TAB_PLUS _T("ReplaceValueName=") TRACE_PLUS TRACE_FMT_STRVALUE
#define TRACE_FMT_ISFUNC_REPLACEPROFSTRING_RESULT			TRACE_FMT_RESULT TRACE_PLUS TRACE_FMT_ISFUNC_REPLACEPROFSTRING

// WriteProfString
#define TRACE_SUB_ISFUNC_WRITEPROFSTRING					_T("WriteProfString")
#define TRACE_FMT_ISFUNC_WRITEPROFSTRING					_T("FileName=") TRACE_FMT_STRVALUE_TAB_PLUS _T("SectionName=") TRACE_FMT_STRVALUE_TAB_PLUS _T("KeyName=") TRACE_FMT_STRVALUE_TAB_PLUS _T("ValueName=") TRACE_PLUS TRACE_FMT_STRVALUE 
#define TRACE_FMT_ISFUNC_WRITEPROFSTRING_RESULT				TRACE_FMT_RESULT TRACE_PLUS TRACE_FMT_ISFUNC_WRITEPROFSTRING

// TextSub Related ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// TextSubSubstitute
#define TRACE_SUB_ISFUNC_TEXTSUBSUBSTITUTE                  _T("TextSubSubstitute")
#define TRACE_FMT_ISFUNC_TEXTSUBSUBSTITUTE		            _T("String=") TRACE_FMT_STRVALUE_TAB_PLUS _T("GlobalOnly=") TRACE_PLUS TRACE_FMT_DECVALUE
#define TRACE_FMT_ISFUNC_TEXTSUBSUBSTITUTE_RESULT           TRACE_FMT_RESULT TRACE_PLUS TRACE_FMT_ISFUNC_TEXTSUBSUBSTITUTE 

// TextSubGetValue
#define TRACE_SUB_ISFUNC_TEXTSUBGETVALUE                    _T("TextSubGetValue")
#define TRACE_FMT_ISFUNC_TEXTSUBGETVALUE					_T("TextSub=") TRACE_FMT_STRVALUE_TAB_PLUS _T("Value=") TRACE_FMT_STRVALUE_TAB_PLUS _T("GlobalOnly=") TRACE_FMT_DECVALUE_TAB_PLUS _T("ResolveEmbedded=") TRACE_PLUS TRACE_FMT_DECVALUE
#define TRACE_FMT_ISFUNC_TEXTSUBGETVALUE_RESULT             TRACE_FMT_RESULT TRACE_PLUS TRACE_FMT_ISFUNC_TEXTSUBGETVALUE

// TextSubSetValue
#define TRACE_SUB_ISFUNC_TEXTSUBSETVALUE                    _T("TextSubSetValue")
#define TRACE_FMT_ISFUNC_TEXTSUBSETVALUE					_T("TextSub=") TRACE_FMT_STRVALUE_TAB_PLUS _T("Value=") TRACE_FMT_STRVALUE_TAB_PLUS _T("Global=") TRACE_PLUS TRACE_FMT_DECVALUE 
#define TRACE_FMT_ISFUNC_TEXTSUBSETVALUE_RESULT             TRACE_FMT_RESULT TRACE_PLUS TRACE_FMT_ISFUNC_TEXTSUBSETVALUE

// Misc Related +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// MaintenanceStart
#define TRACE_SUB_ISFUNC_MAINTENANCESTART					_T("MaintenanceStart")

// DeInstallStart
#define TRACE_SUB_ISFUNC_DEINSTALLSTART					    _T("DeinstallStart")

// VerGetFileVersion
#define TRACE_SUB_ISFUNC_VERGETFILEVERSION                  _T("VerGetFileVersion")
#define TRACE_FMT_ISFUNC_VERGETFILEVERSION					_T("FileName=") TRACE_FMT_STRVALUE_TAB _T("FileVersion=") TRACE_FMT_STRVALUE 
#define TRACE_FMT_ISFUNC_VERGETFILEVERSION_RESULT			TRACE_FMT_RESULT _T("FileName=") TRACE_FMT_STRVALUE
#define TRACE_FMT_ISFUNC_VERGETFILEVERSION_RESULT_ERROR		TRACE_FMT_RESULT_ERROR _T("FileName=") TRACE_FMT_STRVALUE
#define TRACE_FMT_ISFUNC_VERGETFILEVERSION_RESULT_VER		TRACE_FMT_RESULT TRACE_FMT_ISFUNC_VERGETFILEVERSION

// VerGetFileLanguages
#define TRACE_SUB_ISFUNC_VERGETFILELANGUAGES                _T("VerGetFileLanguages")
#define TRACE_FMT_ISFUNC_VERGETFILELANGUAGES				_T("FileName=") TRACE_FMT_STRVALUE
#define TRACE_FMT_ISFUNC_VERGETFILELANGUAGES_RESULT			TRACE_FMT_RESULT TRACE_FMT_ISFUNC_VERGETFILELANGUAGES
#define TRACE_FMT_ISFUNC_VERGETFILELANGUAGES_RESULT_ERROR	TRACE_FMT_RESULT_ERROR TRACE_FMT_ISFUNC_VERGETFILELANGUAGES

// Misc
#define TRACE_SUB_ISFUNC_ISRTHANDLEEXCEPTION                _T("ISRTHandleException")
#define TRACE_FMT_ISFUNC_ISRTHANDLEEXCEPTION_1				_T("Err.Number=") TRACE_FMT_HEXVALUE_TAB_PLUS _T("Err.Source=") TRACE_FMT_STRVALUE_TAB_PLUS _T("Err.Description=") TRACE_FMT_STRVALUE_TAB_PLUS _T("Err.LastDllError=") TRACE_PLUS TRACE_FMT_HEXVALUE
#define TRACE_FMT_ISFUNC_ISRTHANDLEEXCEPTION_2              _T("Caption=") TRACE_FMT_STRVALUE_TAB_PLUS _T("Message=") TRACE_FMT_STRVALUE_TAB_PLUS _T("Abort=") TRACE_FMT_DECVALUE_TAB_PLUS _T("Silent=") TRACE_PLUS TRACE_FMT_DECVALUE

// File Operations *********************************************************
#ifndef _ISCRIPT_VER // Note: IS Compiler has problems with large macros, for now avoid by not compiling this
                     // code when InstallScript is being compiled.

#define TRACE_CAT_FILEOP									_T("ISFileOp")

// Features
#define TRACE_SUB_FILEOP_INSTALLFEATURE_BEGIN				_T("InstallFeatureBegin")
#define TRACE_SUB_FILEOP_INSTALLFEATURE_END					_T("InstallFeatureEnd")
#define TRACE_FMT_FILEOP_INSTALLFEATURE						_T("Feature=") TRACE_FMT_STRVALUE
#define TRACE_FMT_FILEOP_INSTALLFEATURE_RESULT				TRACE_FMT_RESULT TRACE_FMT_FILEOP_INSTALLFEATURE
#define TRACE_FMT_FILEOP_INSTALLFEATURE_RESULT_ERROR		TRACE_FMT_RESULT_ERROR TRACE_FMT_FILEOP_INSTALLFEATURE

// Components
#define TRACE_SUB_FILEOP_INSTALLCOMPONENT_BEGIN				_T("InstallComponentBegin")
#define TRACE_SUB_FILEOP_INSTALLCOMPONENT_END				_T("InstallComponentEnd")
#define TRACE_FMT_FILEOP_INSTALLCOMPONENT                   _T("Component=") TRACE_FMT_STRVALUE
#define TRACE_FMT_FILEOP_INSTALLCOMPONENT_RESULT            TRACE_FMT_RESULT TRACE_FMT_FILEOP_INSTALLCOMPONENT
#define TRACE_FMT_FILEOP_INSTALLCOMPONENT_RESULT_ERROR      TRACE_FMT_RESULT_ERROR TRACE_FMT_FILEOP_INSTALLCOMPONENT
#define TRACE_TXT_FILEOP_COMPONENT_ALREADY_INSTALLED        _T("ComponentAlreadyInstalled")
#define TRACE_TXT_FILEOP_COMPONENT_FILTERED_PLATFORM		_T("ComponentFiltered(Platform)")
#define TRACE_TXT_FILEOP_COMPONENT_FILTERED_LANGUAGE		_T("ComponentFiltered(Language)")

// Files
#define TRACE_SUB_FILEOP_INSTALLFILE_BEGIN					_T("InstallFileBegin")
#define TRACE_SUB_FILEOP_INSTALLFILE_END					_T("InstallFileEnd")
#define TRACE_FMT_FILEOP_INSTALLFILE                        _T("Name") TRACE_FMT_STRVALUE
#define TRACE_FMT_FILEOP_INSTALLFILE_RESULT                 TRACE_FMT_RESULT _T("Name=") TRACE_FMT_FILEOP_INSTALLFILE
#define TRACE_TXT_FILEOP_INSTALLED                          _T("Installed")
#define TRACE_TXT_FILEOP_NOTINSTALLED                       _T("NotInstalled")

// GetTarget
#define TRACE_SUB_FILEOP_GETTARGET							_T("GetTarget")
#define TRACE_FMT_FILEOP_GETTARGET							_T("UnresolvedTarget=") TRACE_FMT_STRVALUE_TAB _T("ResolvedTarget=") TRACE_FMT_STRVALUE

// Shared File
#define TRACE_SUB_FILEOP_SHAREDFILECOUNTINCREMENT			_T("SharedFileCountIncrement")
#define TRACE_FMT_FILEOP_SHAREDFILECOUNTINCREMENT			_T("File=") TRACE_FMT_STRVALUE

// Registration
#define TRACE_SUB_FILEOP_REGISTERFILE						_T("RegisterFile")
#define TRACE_SUB_FILEOP_UNREGISTERFILE						_T("UnRegisterFile")
#define TRACE_FMT_FILEOP_REGISTERFILE						_T("File=") TRACE_FMT_STRVALUE
#define TRACE_FMT_FILEOP_REGISTERFILE_RESULT				TRACE_FMT_RESULT TRACE_FMT_FILEOP_REGISTERFILE 
#define TRACE_FMT_FILEOP_REGISTERFILE_RESULT_ERROR			TRACE_FMT_RESULT_ERROR TRACE_FMT_FILEOP_REGISTERFILE

// .net registration
#define TRACE_SUB_FILEOP_DOTNETREGISTRATION					_T("DotNetRegistration")
#define TRACE_FMT_FILEOP_DOTNETREGISTRATION					_T("RegExe=") TRACE_FMT_STRVALUE_TAB _T("RegCmdLine=") TRACE_FMT_STRVALUE

// Overwrite
#define TRACE_SUB_FILEOP_CHECKOVERWRITE_BEGIN				_T("CheckOverwriteBegin")
#define TRACE_SUB_FILEOP_CHECKOVERWRITE_END					_T("CheckOverwriteEnd")
#define TRACE_FMT_FILEOP_CHECKOVERWRITE_BEGIN				_T("File=") TRACE_FMT_STRVALUE_TAB _T("Overwrite=") TRACE_FMT_HEXVALUE_TAB
#define TRACE_FMT_FILEOP_CHECKOVERWRITE_END					TRACE_FMT_FILEOP_CHECKOVERWRITE_BEGIN _T("OverwriteDetails=") TRACE_FMT_STRVALUE_TAB _T("SourceVerOrDateHigh=") TRACE_FMT_HEXVALUE_TAB _T("SourceVerOrDateLow=") TRACE_FMT_HEXVALUE_TAB _T("TargetVerOrDateHigh=") TRACE_FMT_HEXVALUE_TAB _T("TargetVerOrDateLow=") TRACE_FMT_HEXVALUE_TAB

#define TRACE_TXT_ALWAYSOVERWRITE							_T("AlwaysOverwrite")
#define TRACE_TXT_TARGETFILEDOESNOTEXIST					_T("TargetFileDoesNotExist")
#define TRACE_TXT_NEVEROVERWRITE							_T("NeverOverwrite")
#define TRACE_TXT_TARGETNOVERSION							_T("TargetFileNoVersion")
#define TRACE_TXT_OVERWRITE_EXISTING_VERSION				_T("OverwriteExistingVersion")
#define TRACE_TXT_DONT_OVERWRITE_EXISTING_VERSION			_T("DontOverwriteExistingVersion")
#define TRACE_TXT_TARGETREADFAILURE							_T("TargetReadFailure")
#define TRACE_TXT_OVERWRITE_EXISTING_DATE					_T("OverwriteExistingDate")
#define TRACE_TXT_DONT_OVERWRITE_EXISTING_DATE				_T("DontOverwriteExistingDate")
#define TRACE_TXT_DONT_OVERWRITE_UNKNOWN                    _T("DontOverwriteUnknown")

// CopyFile/CopyFiles
#define TRACE_SUB_FILEOP_COPYFILES_BEGIN					_T("CopyFilesBegin")
#define TRACE_SUB_FILEOP_COPYFILES_END						_T("CopyFilesEnd")
#define TRACE_SUB_FILEOP_COPYFILE_BEGIN						_T("CopyFileBegin")
#define TRACE_SUB_FILEOP_COPYFILE_END						_T("CopyFileEnd")
#define TRACE_FMT_FILEOP_COPYFILES					        _T("Source=") TRACE_FMT_STRVALUE_TAB _T("Target=") TRACE_FMT_STRVALUE
#define TRACE_FMT_FILEOP_COPYFILES_RESULT				    TRACE_FMT_RESULT TRACE_FMT_FILEOP_COPYFILES
#define TRACE_FMT_FILEOP_COPYFILES_RESULT_ERROR			    TRACE_FMT_RESULT_ERROR TRACE_FMT_FILEOP_COPYFILES
#define TRACE_SUB_FILEOP_COPYFILES_ADJUSTTARGET				_T("CopyingFilesAdjustTarget")
#define TRACE_FMT_FILEOP_COPYFILES_ADJUSTTARGET				_T("Target=") TRACE_FMT_STRVALUE

#endif // #ifndef _ISCRIPT_VER
// Shell Objects ************************************************************
#ifndef _ISCRIPT_VER // Note: IS Compiler has problems with large macros, for now avoid by not compiling this
                     // code when InstallScript is being compiled.

#define TRACE_CAT_SHOBJOP									_T("ISShellObjOp")

#define TRACE_TXT_SHORTCUT									_T("Shortcut")
#define TRACE_TXT_INTSHORTCUT								_T("InternetShortcut")

#define TRACE_SUB_SHOBJOP_CREATELINK_BEGIN                  _T("CreateLinkBegin")
#define TRACE_SUB_SHOBJOP_CREATELINK_END			        _T("CreateLinkEnd")
#define TRACE_FMT_SHOBJOP_CREATELINK				        _T("Type=") TRACE_FMT_STRVALUE_TAB _T("ProgramFolder=") TRACE_FMT_STRVALUE_TAB _T("ItemName=") TRACE_FMT_STRVALUE_TAB _T("CommandLine= ") TRACE_FMT_STRVALUE_TAB _T("WorkingDir=") TRACE_FMT_STRVALUE_TAB _T("IconFile=") TRACE_FMT_STRVALUE_TAB _T("IconIndex=") TRACE_FMT_HEXVALUE_TAB _T("ShortcutKey=") TRACE_FMT_STRVALUE_TAB _T("ShowCommand=") TRACE_FMT_HEXVALUE_TAB _T("NotUninstallable=") TRACE_FMT_HEXVALUE
#define TRACE_FMT_SHOBJOP_CREATELINK_RESULT				    TRACE_FMT_RESULT _T("Type=") TRACE_FMT_STRVALUE_TAB _T("ProgramFolder=") TRACE_FMT_STRVALUE_TAB _T("ItemName=") TRACE_FMT_STRVALUE_TAB _T("CommandLine= ") TRACE_FMT_STRVALUE_TAB _T("WorkingDir=") TRACE_FMT_STRVALUE_TAB _T("IconFile=") TRACE_FMT_STRVALUE_TAB _T("IconIndex=") TRACE_FMT_HEXVALUE_TAB _T("ShortcutKey=") TRACE_FMT_STRVALUE_TAB _T("ShowCommand=") TRACE_FMT_HEXVALUE_TAB _T("NotUninstallable=") TRACE_FMT_HEXVALUE

#define TRACE_SUB_SHOBJOP_CREATEFOLDER_BEGIN				_T("CreateFolderBegin")
#define TRACE_SUB_SHOBJOP_CREATEFOLDER_END					_T("CreateFolderEnd")
#define TRACE_FMT_SHOBJOP_CREATEFOLDER					    _T("Folder=") TRACE_FMT_STRVALUE_TAB _T("Shared=") TRACE_FMT_HEXVALUE
#define TRACE_FMT_SHOBJOP_CREATEFOLDER_RESULT				TRACE_FMT_RESULT _T("Folder=") TRACE_FMT_STRVALUE_TAB _T("Shared=") TRACE_FMT_HEXVALUE
#define TRACE_FMT_SHOBJOP_CREATEFOLDER_RESULT_ERROR			TRACE_FMT_RESULT_ERROR _T("Folder=") TRACE_FMT_STRVALUE_TAB _T("Shared=") TRACE_FMT_HEXVALUE

#define TRACE_SUB_SHOBJOP_CREATESHORTCUT_BEGIN				_T("CreateShortcutBegin")
#define TRACE_SUB_SHOBJOP_CREATESHORTCUT_END				_T("CreateShortcutEnd")
#define TRACE_FMT_SHOBJOP_CREATESHORTCUT                    TRACE_FMT_SHOBJOP_CREATELINK

#endif // #ifndef _ISCRIPT_VER
// Registry *****************************************************************
#define TRACE_CAT_REGOP										_T("ISRegistryOp")

// Registry Set +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#define TRACE_SUB_REGOP_INSTALLREGSET_BEGIN					_T("CreateRegistrySetBegin")
#define TRACE_SUB_REGOP_INSTALLREGSET_END					_T("CreateRegistrySetEnd")
#define TRACE_FMT_REGOP_INSTALLREGSET					    _T("Name=") TRACE_FMT_STRVALUE

// CreatingKey ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#define TRACE_SUB_REGOP_CREATEKEY_BEGIN						_T("CreateKeyBegin")
#define TRACE_SUB_REGOP_CREATEKEY_END						_T("CreateKeyEnd")
#define TRACE_FMT_REGOP_CREATEKEY							_T("RootKey=") TRACE_FMT_HEXVALUE_TAB _T("Key=") TRACE_FMT_STRVALUE_TAB _T("Shared=") TRACE_FMT_HEXVALUE

// CreatingValue ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#define TRACE_SUB_REGOP_CREATEVALUE_BEGIN					_T("CreateValueBegin")
#define TRACE_SUB_REGOP_CREATEVALUE_END						_T("CreateValueEnd")
#define TRACE_FMT_REGOP_CREATEVALUE						    _T("RootKey=") TRACE_FMT_HEXVALUE_TAB _T("Key=") TRACE_FMT_STRVALUE_TAB _T("Name=") TRACE_FMT_STRVALUE_TAB _T("Type=") TRACE_FMT_DECVALUE_TAB _T("Data=") TRACE_FMT_STRVALUE

// Text Sub *****************************************************************
#define TRACE_CAT_TXTSUBOP									_T("ISTxtSubOp")

#define TRACE_SUB_TXTSUBOP_GETVALUE							_T("GetValue")
#define TRACE_SUB_TXTSUBOP_PUTVALUE							_T("PutValue")
#define TRACE_SUB_TXTSUBOP_SAVEVALUES						_T("SaveValues")
#define TRACE_SUB_TXTSUBOP_LOADVALUES						_T("LoadValues")

#define TRACE_FMT_TXTSUBOP_GETVALUE					        _T("Name=") TRACE_FMT_STRVALUE_TAB _T("Value=") TRACE_FMT_STRVALUE
#define TRACE_FMT_TXTSUBOP_GETVALUE_RESULT					TRACE_FMT_RESULT TRACE_FMT_TXTSUBOP_GETVALUE
#define TRACE_FMT_TXTSUBOP_GETVALUE_RESULT_ERROR			TRACE_FMT_RESULT_ERROR TRACE_FMT_TXTSUBOP_GETVALUE

#define TRACE_FMT_TXTSUBOP_PUTVALUE					        TRACE_FMT_TXTSUBOP_GETVALUE
#define TRACE_FMT_TXTSUBOP_PUTVALUE_RESULT					TRACE_FMT_TXTSUBOP_GETVALUE_RESULT
#define TRACE_FMT_TXTSUBOP_PUTVALUE_RESULT_ERROR			TRACE_FMT_TXTSUBOP_GETVALUE_RESULT_ERROR

// IScript ******************************************************************
#define TRACE_CAT_ISCRIPTOP									_T("ISiScriptOp")

#define TRACE_SUB_ISCRIPTOP_DLLFUNC_BEGIN					_T("DllFuncBegin")
#define TRACE_SUB_ISCRIPTOP_DLLFUNC_END						_T("DllFuncEnd")
#define TRACE_SUB_ISCRIPTOP_EXPORTEDFUNC_BEGIN			    _T("ExportedFuncBegin")
#define TRACE_SUB_ISCRIPTOP_EXPORTEDFUNC_END			    _T("ExportedFuncEnd")
#define TRACE_FMT_ISCRIPTOP_EXPORTEDFUNC					_T("Function=") TRACE_FMT_STRVALUE

#define TRACE_FMT_ISCRIPTOP_DLLFUNC_1						_T("Library=") TRACE_FMT_STRVALUE TRACE_FMT_TAB _T("Function=") TRACE_FMT_STRVALUE TRACE_FMT_TAB _T("ReturnType=") TRACE_FMT_STRVALUE TRACE_FMT_TAB
#define TRACE_FMT_ISCRIPTOP_DLLFUNC_2						TRACE_FMT_TAB _T("ReturnValue=") TRACE_FMT_DECVALUE TRACE_FMT_TAB TRACE_FMT_GETLASTERROR
#define TRACE_FMT_ISCRIPTOP_DLLFUNC_PARAM_NUMBER            _T("Param%02ld=")

#define TRACE_FMT_ISCRIPTOP_STRING_RETURN					_T("(string)")
#define TRACE_FMT_ISCRIPTOP_STRINGW_RETURN					_T("(stringw)")
#define TRACE_FMT_ISCRIPTOP_POINTER_RETURN					_T("(pointer)")
#define TRACE_FMT_ISCRIPTOP_NUMBER_RETURN					_T("(number)")
#define TRACE_TXT_ISCRIPTOP_BYREF                           _T("(byref)")
#define TRACE_TXT_ISCRIPTOP_BYVAL                           _T("(byval)")

#define TRACE_TXT_ISCRIPTOP_VT_BSTR                         _T("(BSTR)")
#define TRACE_TXT_ISCRIPTOP_VT_LONG                         _T("(long)")

#define TRACE_FMT_ISCRIPTOP_STRING_PARAM					TRACE_FMT_ISCRIPTOP_STRING_RETURN TRACE_FMT_STRVALUE
#define TRACE_FMT_ISCRIPTOP_STRINGW_PARAM					TRACE_FMT_ISCRIPTOP_STRINGW_RETURN TRACE_FMT_STRWVALUE
#define TRACE_FMT_ISCRIPTOP_POINTER_PARAM					TRACE_FMT_ISCRIPTOP_POINTER_RETURN TRACE_FMT_HEXVALUE
#define TRACE_FMT_ISCRIPTOP_NUMBER_PARAM					TRACE_FMT_ISCRIPTOP_NUMBER_RETURN TRACE_FMT_DECVALUE

#define TRACE_SUB_ISCRIPTOP_INVOKEDISPMETHOD	            _T("InvokeDispatchMethod")
#define TRACE_FMT_ISCRIPTOP_INVOKEDISPMETHOD                _T("DispId=") TRACE_FMT_HEXVALUE_TAB _T("Method=") TRACE_FMT_STRVALUE_TAB _T("Flags=") TRACE_FMT_HEXVALUE_TAB _T("Result=") TRACE_FMT_STRVALUE_TAB TRACE_FMT_STRVALUE
#define TRACE_FMT_ISCRIPTOP_INVOKEDISPMETHOD_RESULT         TRACE_FMT_RESULT TRACE_FMT_ISCRIPTOP_INVOKEDISPMETHOD
#define TRACE_FMT_ISCRIPTOP_INVOKEDISPMETHOD_RESULT_ERROR   TRACE_FMT_RESULT_ERROR TRACE_FMT_ISCRIPTOP_INVOKEDISPMETHOD

#define TRACE_SUB_ISCRIPTOP_EXCEPTIONRAISED                 _T("ExceptionRaised")
#define TRACE_FMT_ISCRIPTOP_EXCEPTIONRAISED                 _T("Type=") TRACE_FMT_STRWVALUE_TAB _T("Exception=") TRACE_FMT_HEXVALUE_TAB _T("Description=") TRACE_FMT_STRWVALUE_TAB _T("Source=") TRACE_FMT_STRWVALUE_TAB _T("HelpFile=") TRACE_FMT_STRWVALUE_TAB _T("HelpContext=") TRACE_FMT_DECVALUE

#define TRACE_SUB_ISCRIPTOP_GETEXCEPTIONHANDLER             _T("GetExceptionHandler")
#define TRACE_FMT_ISCRIPTOP_GETEXCEPTIONHANDLER             TRACE_FMT_RESULT_NOTAB

#define TRACE_SUB_ISCRIPTOP_SCRIPT_ACTION                   _T("ScriptAction")
#define TRACE_FMT_ISCRIPTOP_SCRIPT_ACTION                   _T("Type=") TRACE_FMT_STRVALUE

#define TRACE_TXT_ISCRIPTOP_SCRIPT_ACTION_ABORT             _T("abort")
#define TRACE_TXT_ISCRIPTOP_SCRIPT_ACTION_EXIT              _T("exit")

// Exceptions ***************************************************************
#define TRACE_CAT_EXCEPTION                                 _T("ISException") // Note; Hard coded in code - Do not change.
#define TRACE_SUB_EXCEPTION_TRACING_EXTERNAL                _T("ISTracingExternal")
#define TRACE_SUB_EXCEPTION_TRACING_INTERNAL_TRACE          _T("ISTracingInternal_Trace") // Note: Hard coded in code - Do not change.
#define TRACE_SUB_EXCEPTION_TRACING_INTERNAL_TRACEEX        _T("ISTracingInternal_TraceEx") // Note: Hard coded in code - Do not change.
#define TRACE_FMT_EXCEPTION_TRACING_EXTERNAL                _T("File=") TRACE_FMT_STRVALUE_TAB _T("Line=") TRACE_FMT_DECVALUE

// SetupInit ****************************************************************
#define TRACE_CAT_SETUPINIT									_T("ISSetupInit")
#define TRACE_SUB_SETUPINIT_DLLPROCESSATTACH				_T("DLLProcessAttach")
#define TRACE_SUB_SETUPINIT_DLLPROCESSDETACH				_T("DLLProcessDetach")
#define TRACE_FMT_SETUPINIT_DLLPROCESSATTACHDETACH			_T("Library=") TRACE_FMT_STRVALUE

// SetupDLL *****************************************************************
#define TRACE_CAT_SETUPDLLOP								_T("ISSetupDLLOp")

#define TRACE_SUB_SETUPDLLOP_START					        _T("Start")
#define TRACE_FMT_SETUPDLLOP_START				        	_T("WebInvoked=") TRACE_FMT_DECVALUE_TAB _T("CmdLine=") TRACE_FMT_STRVALUE_TAB _T("MediaPath=") TRACE_FMT_STRVALUE_TAB _T("TempDisk1Folder=") TRACE_FMT_STRVALUE

#define TRACE_SUB_SETUPDLLOP_INSTALLFILE_BEGIN		        _T("InstallFileBegin")
#define TRACE_SUB_SETUPDLLOP_INSTALLFILE_END			    _T("InstallFileEnd")
#define TRACE_FMT_SETUPDLLOP_INSTALLFILE				    _T("SourceFile=") TRACE_FMT_STRVALUE_TAB _T("TargetFile=") TRACE_FMT_STRVALUE_TAB _T("InstallFile=") TRACE_FMT_DECVALUE_TAB _T("Authenticate=") TRACE_FMT_DECVALUE_TAB _T("UseMoveFile=") TRACE_FMT_DECVALUE_TAB _T("TypeLib=") TRACE_FMT_DECVALUE
#define TRACE_FMT_SETUPDLLOP_INSTALLFILE_RESULT		        TRACE_FMT_RESULT TRACE_FMT_SETUPDLLOP_INSTALLFILE
#define TRACE_FMT_SETUPDLLOP_INSTALLFILE_RESULT_ERROR       TRACE_FMT_RESULT_ERROR TRACE_FMT_SETUPDLLOP_INSTALLFILE

#define TRACE_SUB_SETUPDLLOP_DOWNLOADFILE_BEGIN		        _T("DownloadFileBegin")
#define TRACE_SUB_SETUPDLLOP_DOWNLOADFILE_END			    _T("DownloadFileEnd")
#define TRACE_FMT_SETUPDLLOP_DOWNLOADFILE				    _T("SourceFile=") TRACE_FMT_STRVALUE_TAB _T("TargetFile=") TRACE_FMT_STRVALUE_TAB _T("UseProgress=") TRACE_FMT_DECVALUE_TAB _T("MakeSureDirExists=") TRACE_FMT_DECVALUE
#define TRACE_FMT_SETUPDLLOP_DOWNLOADFILE_RESULT		    TRACE_FMT_RESULT TRACE_FMT_SETUPDLLOP_DOWNLOADFILE
#define TRACE_FMT_SETUPDLLOP_DOWNLOADFILE_RESULT_ERROR      TRACE_FMT_RESULT_ERROR TRACE_FMT_SETUPDLLOP_DOWNLOADFILE

#define TRACE_SUB_SETUPDLLOP_UNHANDLEDEXCEPTION             _T("UnhandledException")
#define TRACE_FMT_SETUPDLLOP_UNHANDLEDEXCEPTION             _T("ErrorCode=") TRACE_FMT_DECVALUE_TAB _T("Exception=") TRACE_FMT_HEXVALUE_TAB _T("ErrorInformation=") TRACE_FMT_STRVALUE

#define TRACE_SUB_SETUPDLLOP_OPENCAB_BEGIN                  _T("OpenCABBegin")
#define TRACE_SUB_SETUPDLLOP_OPENCAB_END                    _T("OpenCABEnd")
#define TRACE_FMT_SETUPDLLOP_OPENCAB                        _T("HeaderPathFile=") TRACE_FMT_STRVALUE_TAB _T("User=") TRACE_FMT_STRVALUE_TAB _T("Password=") TRACE_FMT_STRVALUE_TAB _T("ProxyUser=") TRACE_FMT_STRVALUE_TAB _T("ProxyPassword=") TRACE_FMT_STRVALUE
#define TRACE_FMT_SETUPDLLOP_OPENCAB_RESULT                 TRACE_FMT_RESULT TRACE_FMT_SETUPDLLOP_OPENCAB
#define TRACE_FMT_SETUPDLLOP_OPENCAB_RESULT_ERROR           TRACE_FMT_RESULT_ERROR TRACE_FMT_SETUPDLLOP_OPENCAB

#define TRACE_SUB_SETUPDLLOP_LOADMEDIAHDR_BEGIN             _T("LoadMediaHdrBegin")
#define TRACE_SUB_SETUPDLLOP_LOADMEDIAHDR_END               _T("LoadMediaHdrEnd")
#define TRACE_FMT_SETUPDLLOP_LOADMEDIAHDR                   _T("HeaderPathFile=") TRACE_FMT_STRVALUE
#define TRACE_FMT_SETUPDLLOP_LOADMEDIAHDR_RESULT            TRACE_FMT_RESULT TRACE_FMT_SETUPDLLOP_LOADMEDIAHDR
#define TRACE_FMT_SETUPDLLOP_LOADMEDIAHDR_RESULT_ERROR      TRACE_FMT_RESULT_ERROR TRACE_FMT_SETUPDLLOP_LOADMEDIAHDR

#define TRACE_TXT_SETUPDLLOP_LOADMEDIAHDR_ERROR_OPEN    	_T("ErrorOpeningHeader")
#define TRACE_TXT_SETUPDLLOP_LOADMEDIAHDR_ERROR_COPYTOTEMP  _T("ErrorCopyingToTemp")
#define TRACE_TXT_SETUPDLLOP_LOADMEDIAHDR_ERROR_OPENFROMTEMP    _T("ErrorOpeningFromTemp")
#define TRACE_TXT_SETUPDLLOP_LOADMEDIAHDR_ERROR_READ_1      _T("ErrorReadingHeader_1")
#define TRACE_TXT_SETUPDLLOP_LOADMEDIAHDR_ERROR_READ_2      _T("ErrorReadingHeader_2")
#define TRACE_TXT_SETUPDLLOP_LOADMEDIAHDR_ERROR_READ_3      _T("ErrorReadingHeader_3")
#define TRACE_TXT_SETUPDLLOP_LOADMEDIAHDR_ERROR_READ_4      _T("ErrorReadingHeader_4")
#define TRACE_TXT_SETUPDLLOP_LOADMEDIAHDR_ERROR_MEM         _T("ErrorAllocatingMemory")
#define TRACE_TXT_SETUPDLLOP_LOADMEDIAHDR_ERROR_SIG_VER     _T("InvalidMediaSignatureOrVersion")
#define TRACE_TXT_SETUPDLLOP_LOADMEDIAHDR_ERROR_UNKNOWN     _T("UnknownException")

// Log **********************************************************************
#define TRACE_CAT_LOGOP										_T("ISLogOp")

#define TRACE_TXT_LOGOP_LOGGED								_T("Logged")
#define TRACE_TXT_LOGOP_NOTLOGGED							_T("NotLogged")

#define TRACE_FMT_RESULT_LOGOP								TRACE_FMT_RESULT

// General ******************************************************************
#define TRACE_CAT_GENERALOP									_T("ISGeneralOp")

#endif